title: The Shade
description: Personal Blog and Portfolio
theme: null
author: Andrew Martinez
url: "https://andrewmartinez.dev"

include:
  - assets

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
permalink: /blog/:year/:month/:day/:title.html
