project:
  type: website
  output-dir: docs
  
website:
  title: "Andrew Martinez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/andrew-j-martinez/
      - icon: github
        href: https://github.com/AndrewJMart
  page-footer:
    left: "&copy; Copyright 2024, Andrew Martinez"

format:
  html:
    theme: cerulean
    toc: true

editor: source

