project:
  type: website
  output-dir: docs
  
website:
  title: "Andrew Martinez"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "More"
        menu:
          - projects.qmd
          - blogs.qmd
  page-footer:
    left: "&copy; Copyright 2024, Andrew Martinez"

format:
  html:
    theme: Litera
    toc: true

editor: source

